# Locate SDL2_mixer library
# This module defines
# SDL2_MIXER_INCLUDE_DIR  = where SDL_mixer.h can be found
# SDL2_MIXER_LIBRARY      = the library to link against SDL2_mixer
# SDL2_MIXER_FOUND        = set to 1 if SDL2_mixer is found

IF(SDL2_mixer_INCLUDE_DIRS)

  FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL2/SDL_mixer.h ${SDL2_mixer_INCLUDE_DIRS})
  FIND_LIBRARY(SDL2_MIXER_LIBRARY SDL2_mixer ${SDL2_mixer_LIBRARY_DIRS})

ELSE(SDL2_mixer_INCLUDE_DIRS)

  SET(TRIAL_LIBRARY_PATHS
    $ENV{SDL2_MIXER_HOME}/lib
    /usr/lib
    /usr/local/lib
    /sw/lib
  )
  SET(TRIAL_INCLUDE_PATHS
    $ENV{SDL2_MIXER_HOME}/include/SDL2
    /usr/include/SDL2
    /usr/local/include/SDL2
    /sw/include/SDL2
  )

  FIND_LIBRARY(SDL2_MIXER_LIBRARY SDL2_mixer ${TRIAL_LIBRARY_PATHS})
  FIND_PATH(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h ${TRIAL_INCLUDE_PATHS})

ENDIF(SDL2_mixer_INCLUDE_DIRS)

IF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 1 CACHE BOOL "Found SDL2_mixer library")
ELSE(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 0 CACHE BOOL "Not found SDL2_mixer library")
ENDIF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)

MARK_AS_ADVANCED(
  SDL2_MIXER_INCLUDE_DIR
  SDL2_MIXER_LIBRARY
  SDL2_MIXER_FOUND
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_MIXER REQUIRED_VARS SDL2_MIXER_INCLUDE_DIR SDL2_MIXER_LIBRARY)
